time-tracker-db:
  image: postgres:13-alpine
  environment:
    - POSTGRES_USER=web-automation
    - POSTGRES_PASSWORD=super-secret-pass
  ports:
    - "5432:5432"
  volumes:
    - ./data:/var/lib/postgresql/data